### ISSUE TITLE
how to compare functions from this to d07RiV and to DevolutionX?

### ISSUE THREAD

**Issue by Benman2785** [JohnImril/diablo_web#47]
Hi,

what are the differences to d07RiV:
so far i noticed its "faster" and maybe using more than 20fps

**Comment by JohnImril** [comment]
1. Rewritten with Modern Technologies: The project has been completely rewritten using Vite and TypeScript, replacing the older build system and JavaScript codebase. This modernization enhances development speed and code reliability.

2. Node.js v22 Compatibility: The new project addresses compatibility issues with Node.js version 22, which were present in the original DiabloWeb. This ensures that developers using the latest Node.js can work without hindrance.

3. Dependency Removal: Lots of unnecessary dependencies have been removed. The code now exposes a minimal required interface with JavaScript.

4. Updated and Refactored Codebase: The code has been refactored for better performance and reliability. Dependencies are updated, and obsolete or unnecessary code has been cleaned up.

5. Improved Build System with Vite: Using Vite as the build tool provides faster development server start times and quicker hot module replacement, enhancing the development experience.

6. Type Safety with TypeScript: Incorporating TypeScript introduces strong typing, which helps catch errors at compile time and makes the codebase more maintainable.

7. Community Contributions and Maintenance: By updating the project and making it more accessible, the new version invites community contributions and is easier to maintain and extend.

Summary:
This project diverges from the original DiabloWeb by overhauling the build system with Vite, rewriting the codebase in TypeScript, ensuring compatibility with newer Node.js versions, removing dependencies, and enhancing event handling. These changes result in a modernized, more efficient, and more accessible version of the game that stays true to the classic Diablo experience while leveraging contemporary web development tools.

Plans:
I'm thinking about paying a designer to create a nice looking start page and maybe remove some extra dependencies from the code

For example, about dependencies:
![image](https://github.com/user-attachments/assets/78e911f0-a10e-4779-b16e-9991f08c02ac)
![image](https://github.com/user-attachments/assets/c4ad73d8-3572-48dd-8aa4-d08c6447c605)
and on the second screenshot it's not even all, but for the most part it's just extra library code that can be thrown away

**Comment by Benman2785** [comment]
thank you for your detailed answer.

and i can say it is way more performant :)

**Comment by Benman2785** [comment]
thank you for helping me with all my questions :)
