### ISSUE TITLE
aspect ratio 16:9 possible?

### ISSUE THREAD

**Issue by Benman2785** [JohnImril/diablo_web#52]
hi,

is it possible to "stretch" the game to screen? EDIT: YES it is => https://github.com/JohnImril/diablo_web/issues/52#issuecomment-2474492437
maybe add a toggle to switch from 4:3 to "fit-screen"?

i dont know if its wasm or if its a simple css width & height =100%

**Comment by JohnImril** [comment]
Hi, you can stretch the image using CSS, but it loses its aspect ratio and looks ugly. As far as I saw, the DevilutionX project was able to somehow solve this problem, but to take it from them I need to completely disassemble their project and regenerate the source files for my project. This is not possible in the near future

**Comment by Benman2785** [comment]
works fine!

how2:
open index-***.css
searchfor: >@media (max-aspect-ratio: 640/480){.app__body{left:0;right:0;width:auto;top:calc(50% - 37.5vw);height:75vw}<
replace with: >@media {.app__body{left:0;right:0;width:auto;top:0;height:100vh}.app__body-v{left:0;right:0;width:auto}}<

**Comment by Benman2785** [comment]
would be nice to have a toggle button for this "strech to screen" vs "4:3"- best even if in the game (like WebRTC)

**Comment by Benman2785** [comment]
if replaced with 

> @media (max-aspect-ratio: 854/480){.app__body{left:0;right:0;width:auto;top:0;height:100vh}

it is 4:3 when loaded normal in browser and 100% stretched if pressing F11 (tested on 1080p 16:9 monitor)
would be nice if you could test this with 16:10 and higher resolutions than 1080p too :)

**Comment by JohnImril** [comment]
are you sure it looks normal? and f11 is the standard browser behavior that turns on full-screen mode, but not stretching, you can of course do this through some checkbox when starting the application or some other button other than f11, but for some reason it reminds me of the video Kanye West & Lil Pump - I Love It feat. Adele Givens [Official Music Video]. Maybe it's better to take a look at how they did it in the DevilutionX project

**Comment by Benman2785** [comment]
a native dynamic aspect-ration would be nice - but for me is no must
i am fine if i have a toggle/hotkey to switch from "4:3" to "stretched" - as it is easy to implement:

1. add duplicate css settings and add "_4to3" & "_stretched" to them
2. add a function to webpage that if a specified key is pressed it uses either "_4to3" or "_stretched" css

https://unixpapa.com/js/key.html may help with this

**Comment by Benman2785** [comment]
here a bad java script to toggle 16:9 & 4:3 when pressing F11

// Toggle for Aspect Ratio (4:3 / 16:9)
let isWide = false;  // Default to 4:3

// Function to toggle aspect ratio
function toggleAspectRatio() {
  const appBodyInner = document.querySelector('.app__inner');

  if (isWide) {
    // Set to 4:3 aspect ratio
    appBodyInner.style.width = '75vw';
    appBodyInner.style.maxHeight = 'calc(75vw * 0.75)';
  } else {
    // Set to 16:9 aspect ratio (Fullscreen)
    appBodyInner.style.width = '100vw';
    appBodyInner.style.height = '100vh';
  }

  // Toggle the state
  isWide = !isWide;
}

// Listen for key press to toggle aspect ratio
document.addEventListener('keydown', function(event) {
  if (event.key === 'F11') {  // Use 'F11' to toggle the aspect ratio
    toggleAspectRatio();
  }
});


with css:
.app__inner {
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  width: 75vw; /* Default 4:3 aspect ratio */
  height: auto;
  max-height: calc(75vw * 0.75); /* 4:3 aspect ratio */
  transition: width 0.3s, height 0.3s; /* Smooth transition */
}

**Comment by Benman2785** [comment]
this here needs to be added to index*.js

if you press F11 you toogle between "stretch" and 4:3

> // Toggle for Aspect Ratio (4:3 / 16:9)
> let isWide = false; // Default to 4:3
> 
> // Function to toggle aspect ratio
> function toggleAspectRatio() {
> const appBodyInner = document.querySelector('.app__inner');
> const appBodyOuter = document.querySelector('.app__body');
> 
> if (isWide) {
> // Set to 4:3 aspect ratio
> appBodyInner.style.width = 'calc(400vh / 3)';
> appBodyInner.style.maxHeight = 'calc(75vw * 0.75)';
> appBodyOuter.style.left = 'calc(50% - 200vh / 3)';
> } else {
> // Set to 16:9 aspect ratio (Fullscreen)
> appBodyInner.style.width = '100vw';
> appBodyInner.style.height = '100vh';
> appBodyOuter.style.left = '0';
> }
> 
> // Toggle the state
> isWide = !isWide;
> }
> 
> // Listen for key press to toggle aspect ratio
> document.addEventListener('keydown', function(event) {
> if (event.key === 'F11') { // Use 'F11' to toggle the aspect ratio
> toggleAspectRatio();
> }
> });

**Comment by Benman2785** [comment]
thank you in advance :)

**Comment by JohnImril** [comment]
added this feature to diablo_web_simple assigned to F9, take a look

**Comment by JohnImril** [comment]
added this feature to diablo_web_simple assigned to F9, take a look
